# Generated by Django 4.2.6 on 2023-10-26 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_alter_person_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='firstname',
            new_name='p_firstname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='id',
            new_name='p_id',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='lastname',
            new_name='p_lastname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='picture',
            new_name='p_picture',
        ),
    ]
