# Generated by Django 4.2.6 on 2023-11-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_rename_firstname_person_p_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='p_regisyear',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='p_tel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
